services:
  asr-indic-server:
    image: slabstech/asr_indic_server
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    environment:
      - LANGUAGE=kn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7860/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh